server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: hackathon-ldt-backend
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /swagger.json

logging:
  level:
    org.springframework.security: INFO

application:
  security:
    jwt:
      secret-key: 77217A25432A462D4A614E645267556B58703272357538782F413F4428472B4B
      expiration: 900000
      refresh-token:
        expiration: 604800000
  headers:
    pagination: X-Total-Count