server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: hackathon-ldt-backend
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /swagger.json

headers:
  pagination: X-Total-Count