server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: hackathon-ldt-backend
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          vk:
            provider: vk
            client-id: 51652597
            client-secret: KdQ4SXyJSS2JhI1QmqKE
            redirect-uri: http://localhost:8080
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: email, wall, friends
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize?revoke=1
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=5.131&fields=photo_max
            user-name-attribute: email

springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /swagger.json

logging:
  level:
    org.springframework.security: INFO

application:
  security:
    jwt:
      secret-key: 77217A25432A462D4A614E645267556B58703272357538782F413F4428472B4B
      expiration: 900000
      refresh-token:
        expiration: 604800000